import React, { useState, useEffect } from 'react';
import { Job } from '../App';
import { JobResults } from './JobResults';
import { bioinformaticsAPI, mapApiStatusToFrontend } from '../services/api';
import './JobDashboard.css';

interface JobDashboardProps {
  jobs: Job[];
}

const JobDashboard: React.FC<JobDashboardProps> = ({ jobs }) => {
  const [selectedJob, setSelectedJob] = useState<string | null>(null);
  const [jobDetails, setJobDetails] = useState<{[key: string]: any}>({});

  // ✅ NEW: Load job details for completed jobs automatically
  useEffect(() => {
    const loadCompletedJobsDetails = async () => {
      const completedJobs = jobs.filter(job =>
        job.status === 'completed' && !jobDetails[job.id]
      );

      for (const job of completedJobs) {
        try {
          console.log('🔄 Auto-loading details for completed job:', job.id);
          const data = await bioinformaticsAPI.getJob(job.id);
          setJobDetails(prev => ({ ...prev, [job.id]: data }));
        } catch (error) {
          console.error('❌ Error auto-loading job details:', error);
        }
      }
    };

    loadCompletedJobsDetails();
  }, [jobs, jobDetails]);

  // ✅ ENHANCED: Status utilities with better debugging
  const getStatusColor = (status: Job['status']) => {
    const colorMap = {
      'completed': '#4caf50',
      'running': '#2196f3',
      'error': '#f44336',
      'pending': '#ff9800'
    };
    return colorMap[status] || '#ff9800';
  };

  const getStatusText = (status: Job['status']) => {
    const textMap = {
      'completed': 'COMPLETED',
      'running': 'PROCESSING',
      'error': 'FAILED',
      'pending': 'PENDING'
    };
    return textMap[status] || 'PENDING';
  };

  // ✅ ENHANCED: Download function with better error handling
  const downloadFileWithFallback = async (fileKey: string, displayName: string) => {
    try {
      console.log(`📥 Downloading file: ${fileKey}`);
      const data = await bioinformaticsAPI.downloadFile(fileKey);

      if (data.downloadUrl) {
        console.log('🔗 Opening download URL:', data.downloadUrl);

        // ✅ FIXED: Use a more reliable download method
        const link = document.createElement('a');
        link.href = data.downloadUrl;
        link.target = '_blank';
        link.rel = 'noopener noreferrer';
        link.download = displayName;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      } else {
        console.warn('⚠️ No download URL available');
        alert(`Download not available for "${displayName}".`);
      }
    } catch (error: any) {
      console.error('❌ Download failed:', error);

      // ✅ IMPROVED: Better error messages
      if (error.message === 'FILE_NOT_FOUND') {
        alert(`The file "${displayName}" was not found on the server.\n\nThis file may not have been generated by the analysis.`);
      } else if (error.message.includes('Network Error') || error.message.includes('CORS')) {
        alert(`CORS Error: Unable to download file.\n\nPlease try the following:\n1. Check if the file exists in S3\n2. Contact administrator to enable CORS\n3. Try downloading directly from AWS Console`);
      } else if (error.response?.status === 403) {
        alert(`Access Denied (403): You don't have permission to download this file.\n\nThis may be a CORS configuration issue.`);
      } else {
        alert(`Unable to download "${displayName}". Error: ${error.message}`);
      }
    }
  };

  // ✅ ENHANCED: Get correct file keys with better analysis type detection
  const getQuickDownloadKeys = (jobId: string, jobData: any) => {
    console.log('📁 Getting quick download keys for:', { jobId, jobData });

    // Determine analysis type from multiple sources
    const analysisType = jobData?.analysisType?.toLowerCase() ||
                        jobData?.type?.toLowerCase() ||
                        'fastqc';

    console.log('🎯 Detected analysis type:', analysisType);

    // ✅ PRIORITY 1: Use availableFiles from backend if provided
    if (jobData?.availableFiles && Object.keys(jobData.availableFiles).length > 0) {
      console.log('✅ Using availableFiles from backend:', jobData.availableFiles);
      return jobData.availableFiles;
    }

    // ✅ PRIORITY 2: Check resultFiles array for actual existing files
    if (jobData?.resultFiles && Array.isArray(jobData.resultFiles) && jobData.resultFiles.length > 0) {
      console.log('✅ Using resultFiles array:', jobData.resultFiles);
      const availableFiles: any = {};

      jobData.resultFiles.forEach((file: string) => {
        if (file.includes('fastqc') && file.endsWith('.html')) availableFiles.html = file;
        else if (file.includes('fastqc') && file.endsWith('.zip')) availableFiles.zip = file;
        else if (file.includes('blast') && file.endsWith('.txt')) availableFiles.txt = file;
        else if (file.endsWith('.html')) availableFiles.html = file;
        else if (file.endsWith('.zip')) availableFiles.zip = file;
        else if (file.endsWith('.txt')) availableFiles.txt = file;
        else if (file.endsWith('.fasta')) availableFiles.fasta = file;
      });

      // If we found files, use them
      if (Object.keys(availableFiles).length > 0) {
        return availableFiles;
      }
    }

    // ✅ PRIORITY 3: Fallback to standard file paths
    if (analysisType === 'blast') {
      const blastFiles = {
        txt: `${jobId}/blast_report.txt`,
        fasta: `${jobId}/input_sequence.fasta`
      };
      console.log('🔬 Using BLAST fallback files:', blastFiles);
      return blastFiles;
    } else {
      // FastQC - both files should exist
      const fastqcFiles = {
        html: `${jobId}/input_fastqc.html`,
        zip: `${jobId}/input_fastqc.zip`,
      };
      console.log('🔍 Using FastQC fallback files:', fastqcFiles);
      return fastqcFiles;
    }
  };

  // ✅ ENHANCED: Render download buttons with better state handling
  const renderDownloadButtons = (jobId: string, jobData: any) => {
    const fileKeys = getQuickDownloadKeys(jobId, jobData);
    const analysisType = jobData?.analysisType?.toLowerCase() ||
                        jobData?.type?.toLowerCase() ||
                        'fastqc';

    console.log('🎨 Rendering download buttons:', { jobId, analysisType, fileKeys });

    const handleDownload = (fileType: string, fileKey: string | undefined, displayName: string) => {
      if (fileKey) {
        downloadFileWithFallback(fileKey, displayName);
      } else {
        console.warn(`❌ File key not available for type: ${fileType}`);
        alert(`Download not available. The ${fileType} file was not generated.`);
      }
    };

    if (analysisType === 'blast') {
      return (
        <div className="quick-downloads">
          {fileKeys.txt && (
            <button
              onClick={() => handleDownload('txt', fileKeys.txt, `blast_report_${jobId}.txt`)}
              className="download-btn txt-btn"
              title="Download BLAST Report"
            >
              📄 BLAST Report
            </button>
          )}
          {fileKeys.fasta && (
            <button
              onClick={() => handleDownload('fasta', fileKeys.fasta, `sequence_${jobId}.fasta`)}
              className="download-btn fasta-btn"
              title="Download Sequence File"
            >
              🧬 Sequence
            </button>
          )}
          {/* Show message if no files available */}
          {!fileKeys.txt && !fileKeys.fasta && (
            <div className="no-files-message">
              <small>No downloadable files available</small>
            </div>
          )}
        </div>
      );
    } else {
      // FastQC - show available files
      return (
        <div className="quick-downloads">
          {fileKeys.html && (
            <button
              onClick={() => handleDownload('html', fileKeys.html, `report_${jobId}.html`)}
              className="download-btn html-btn"
              title="Download HTML Report"
            >
              📄 HTML Report
            </button>
          )}
          {fileKeys.zip && (
            <button
              onClick={() => handleDownload('zip', fileKeys.zip, `data_${jobId}.zip`)}
              className="download-btn zip-btn"
              title="Download ZIP Data"
            >
              📦 ZIP Data
            </button>
          )}
          {/* Show message if no files available */}
          {!fileKeys.html && !fileKeys.zip && (
            <div className="no-files-message">
              <small>No downloadable files available</small>
            </div>
          )}
        </div>
      );
    }
  };

  // ✅ ENHANCED: Fetch detailed job information with status mapping
  const fetchJobDetails = async (jobId: string) => {
    try {
      console.log('🔍 Fetching details for job:', jobId);
      const data = await bioinformaticsAPI.getJob(jobId);
      console.log('✅ Raw job details received:', data);

      // Map the status for consistent display
      const mappedData = {
        ...data,
        // Ensure status is mapped for consistent display in JobResults
        mappedStatus: mapApiStatusToFrontend(data.status)
      };

      setJobDetails(prev => ({ ...prev, [jobId]: mappedData }));
      setSelectedJob(selectedJob === jobId ? null : jobId);
    } catch (error) {
      console.error('❌ Error fetching job details:', error);
      alert('Failed to fetch job details. Please try again.');
    }
  };

  if (jobs.length === 0) {
    return (
      <div className="job-dashboard">
        <h2>Analysis Jobs</h2>
        <p className="no-jobs">No jobs yet. Upload a file to get started!</p>
      </div>
    );
  }

  return (
    <div className="job-dashboard">
      <h2>Analysis Jobs ({jobs.length})</h2>

      {/* ✅ ADDED: CORS Warning Banner */}
      <div className="cors-warning" style={{
        background: '#fff3cd',
        border: '1px solid #ffeaa7',
        borderRadius: '6px',
        padding: '12px',
        marginBottom: '20px',
        color: '#856404'
      }}>
        <strong>⚠️ CORS Warning:</strong> File downloads may fail due to CORS restrictions.
        If downloads fail, please contact the administrator to enable CORS on the API Gateway.
      </div>

      <div className="jobs-list">
        {jobs.map((job, index) => {
          const jobData = jobDetails[job.id];
          const analysisType = jobData?.analysisType?.toLowerCase() ||
                             jobData?.type?.toLowerCase() ||
                             job.type.toLowerCase();

          console.log('🎯 Rendering job card:', {
            jobId: job.id,
            frontendStatus: job.status,
            hasJobData: !!jobData,
            jobDataStatus: jobData?.status,
            analysisType
          });

          return (
            <div key={`${job.id}-${index}`} className="job-card">
              <div className="job-header">
                <span className="job-filename">{job.filename}</span>
                <span
                  className="job-status"
                  style={{ backgroundColor: getStatusColor(job.status) }}
                >
                  {getStatusText(job.status)}
                </span>
              </div>

              <div className="job-details">
                <span>Type: {analysisType.toUpperCase()}</span>
                <span>Started: {job.createdAt.toLocaleString()}</span>
                <span>ID: {job.id.substring(0, 8)}...</span>
                {job.batchJobId && <span>Batch: {job.batchJobId.substring(0, 8)}...</span>}

                {/* ✅ ADDED: Job data status indicator */}
                <span style={{
                  color: jobData ? '#28a745' : '#6c757d',
                  fontSize: '0.8rem'
                }}>
                  Details: {jobData ? 'Loaded' : 'Not Loaded'}
                </span>
              </div>

              {(job.status === 'completed' || job.status === 'running' || job.status === 'error') && (
                <div className="job-actions">
                  <button
                    className="view-results-btn"
                    onClick={() => fetchJobDetails(job.id)}
                  >
                    {selectedJob === job.id ? 'Hide Details' : 'View Details'}
                  </button>

                  {job.status === 'completed' && renderDownloadButtons(job.id, jobData)}

                  {job.status === 'error' && (
                    <div className="error-message">
                      <span>❌ Processing failed. Check AWS Batch for details.</span>
                    </div>
                  )}
                </div>
              )}

              {/* Show detailed results when selected */}
              {selectedJob === job.id && jobDetails[job.id] && (
                <div className="job-results-container">
                  <JobResults
                    jobId={job.id}
                    jobData={jobDetails[job.id]}
                  />
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default JobDashboard;