import React from 'react';
import { bioinformaticsAPI, mapApiStatusToFrontend } from '../services/api';

interface JobResultsProps {
  jobId: string;
  jobData: any;
}

export const JobResults: React.FC<JobResultsProps> = ({ jobId, jobData }) => {
  // ✅ ENHANCED: Debug the incoming data with status mapping
  console.log('🔍 JobResults Debug:', {
    jobId,
    jobData,
    rawStatus: jobData?.status,
    mappedStatus: jobData?.status ? mapApiStatusToFrontend(jobData.status) : 'unknown',
    analysisType: jobData?.analysisType,
    fileName: jobData?.fileName,
    resultFiles: jobData?.resultFiles
  });

  // Determine the actual status for display
  const actualStatus = jobData?.status ? mapApiStatusToFrontend(jobData.status) : 'unknown';
  console.log('🎯 Actual status for display:', actualStatus);

  // ✅ FIXED: Use API service for downloads
  const downloadFileWithFallback = async (fileKey: string, displayName: string) => {
    try {
      const data = await bioinformaticsAPI.downloadFile(fileKey);

      if (data.downloadUrl) {
        console.log('🔗 Opening download URL');
        window.open(data.downloadUrl, '_blank');
      } else {
        console.warn('⚠️ No download URL available');
        alert(`Download not available for "${displayName}".`);
      }
    } catch (error: any) {
      console.warn('⚠️ Download failed:', error);

      if (error.message === 'FILE_NOT_FOUND') {
        alert(`The file "${displayName}" is not available for download.\n\nThis file was not generated by the analysis.`);
      } else {
        alert(`Unable to download "${displayName}". Please try again.`);
      }
    }
  };

  // ✅ IMPROVED: Better analysis type detection
  const detectAnalysisType = (): string => {
    // Method 1: Check analysisType field
    if (jobData?.analysisType) {
      return jobData.analysisType.toLowerCase();
    }

    // Method 2: Check file name
    if (jobData?.fileName) {
      const fileName = jobData.fileName.toLowerCase();
      if (fileName.endsWith('.fasta') || fileName.endsWith('.fa') || fileName.endsWith('.fna')) {
        return 'blast';
      }
      if (fileName.endsWith('.fastq') || fileName.endsWith('.fq')) {
        return 'fastqc';
      }
    }

    // Method 3: Check result files
    if (jobData?.resultFiles && Array.isArray(jobData.resultFiles)) {
      const hasBlastFiles = jobData.resultFiles.some((f: string) =>
        f.includes('blast') || f.endsWith('.txt')
      );
      const hasFastQCFiles = jobData.resultFiles.some((f: string) =>
        f.includes('fastqc') || f.endsWith('.html') || f.endsWith('.zip')
      );

      if (hasBlastFiles) return 'blast';
      if (hasFastQCFiles) return 'fastqc';
    }

    // Default fallback
    return 'fastqc';
  };

  const analysisType = detectAnalysisType();
  console.log('🎯 Detected analysis type:', analysisType);

  // ✅ FIXED: Type-safe file keys interface
  interface FileKeys {
    html?: string;
    zip?: string;
    txt?: string;
    fasta?: string;
    summary?: string;
  }

  // ✅ FIXED: Get correct file keys - SIMPLIFIED VERSION
  const getFileKeys = (): FileKeys => {
    console.log('📁 Getting file keys for:', analysisType);

    // Use availableFiles from backend if provided
    if (jobData?.availableFiles && Object.keys(jobData.availableFiles).length > 0) {
      console.log('✅ Using availableFiles from backend:', jobData.availableFiles);
      return jobData.availableFiles;
    }

    // For BLAST jobs - ONLY use these file paths
    if (analysisType === 'blast') {
      return {
        txt: `${jobId}/blast_report.txt`,
      };
    }

    // For FastQC jobs
    return {
      html: `${jobId}/input_fastqc.html`,
      zip: `${jobId}/input_fastqc.zip`,
    };
  };

  const fileKeys = getFileKeys();
  console.log('📋 Final file keys:', fileKeys);

  // ✅ FIXED: Safe download handler with null checks
  const handleDownload = (fileType: keyof FileKeys, defaultFileName: string) => {
    const fileKey = fileKeys[fileType];
    if (fileKey) {
      downloadFileWithFallback(fileKey, defaultFileName);
    } else {
      console.warn(`❌ File key not available for type: ${fileType}`);
      alert(`Download not available. The ${fileType} file was not generated.`);
    }
  };

  // ✅ ENHANCED: Check if job is actually completed
  const isJobCompleted = actualStatus === 'completed';
  console.log('📊 Job completion status:', { actualStatus, isJobCompleted });

  // If job is not completed, don't show results
  if (!jobData || !isJobCompleted) {
    return (
      <div className="job-results">
        <h3>📊 Analysis Details</h3>
        <div className="job-info">
          <p><strong>Status:</strong> {actualStatus.toUpperCase()}</p>
          <p><strong>Job ID:</strong> {jobId}</p>
          <p><strong>File:</strong> {jobData?.fileName || 'Unknown'}</p>
          <p><strong>Type:</strong> {analysisType.toUpperCase()}</p>
          {jobData?.createdAt && (
            <p><strong>Created:</strong> {new Date(jobData.createdAt).toLocaleString()}</p>
          )}
        </div>
        {actualStatus === 'running' && (
          <div className="processing-message">
            <p>⏳ Analysis is still processing... Check back soon!</p>
          </div>
        )}
      </div>
    );
  }

  // ✅ FIXED: Render only BLAST files for BLAST jobs with safe handlers
  const renderResultCards = () => {
    console.log('🎨 Rendering cards for:', analysisType);

    if (analysisType === 'blast') {
      return (
        <div className="results-grid">
          {/* BLAST Report - Only this should exist */}
          <div className="result-card">
            <div className="result-header">
              <span className="result-icon">📄</span>
              <h4>BLAST Report</h4>
            </div>
            <p>BLAST analysis results and alignment data</p>
            <button
              onClick={() => handleDownload('txt', `blast_report_${jobId}.txt`)}
              className="download-btn txt-btn"
            >
              Download BLAST Report
            </button>
            <div className="file-info">
              <small>File: {fileKeys.txt || 'blast_report.txt'}</small>
            </div>
          </div>

          {/* Optional: Show debug info */}
          <div className="result-card debug-card">
            <div className="result-header">
              <span className="result-icon">🐛</span>
              <h4>Debug Info</h4>
            </div>
            <div className="debug-info">
              <p><strong>Analysis Type:</strong> {analysisType}</p>
              <p><strong>Input File:</strong> {jobData.fileName}</p>
              <p><strong>Available Files:</strong> {jobData.resultFiles?.join(', ') || 'None'}</p>
              <p><strong>Status:</strong> {actualStatus}</p>
            </div>
          </div>
        </div>
      );
    } else {
      // FastQC
      return (
        <div className="results-grid">
          {/* HTML Report */}
          <div className="result-card">
            <div className="result-header">
              <span className="result-icon">📄</span>
              <h4>HTML Report</h4>
            </div>
            <p>Interactive quality control report</p>
            <button
              onClick={() => handleDownload('html', `fastqc_report_${jobId}.html`)}
              className="download-btn html-btn"
            >
              Download HTML
            </button>
          </div>

          {/* ZIP Data */}
          <div className="result-card">
            <div className="result-header">
              <span className="result-icon">📦</span>
              <h4>Raw Data</h4>
            </div>
            <p>Complete analysis data (ZIP)</p>
            <button
              onClick={() => handleDownload('zip', `fastqc_data_${jobId}.zip`)}
              className="download-btn zip-btn"
            >
              Download ZIP
            </button>
          </div>
        </div>
      );
    }
  };

  return (
    <div className="job-results">
      <h3>📊 Analysis Results ({analysisType.toUpperCase()})</h3>

      <div className="job-info">
        <p><strong>Status:</strong> {actualStatus.toUpperCase()}</p>
        <p><strong>Job ID:</strong> {jobId}</p>
        <p><strong>File:</strong> {jobData.fileName}</p>
        <p><strong>Type:</strong> {analysisType.toUpperCase()}</p>
        <p><strong>Completed:</strong> {new Date(jobData.updatedAt || jobData.createdAt).toLocaleString()}</p>
      </div>

      {renderResultCards()}

      <style>{`
        .job-results {
          margin-top: 1rem;
          padding: 1.5rem;
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          background: white;
        }

        .job-results h3 {
          margin: 0 0 1.5rem 0;
          font-size: 1.5rem;
          color: #2d3748;
        }

        .job-info {
          background: #f7fafc;
          padding: 1rem;
          border-radius: 6px;
          margin-bottom: 1.5rem;
          border-left: 4px solid #4299e1;
        }

        .job-info p {
          margin: 0.25rem 0;
          color: #4a5568;
        }

        .processing-message {
          background: #fff3cd;
          border: 1px solid #ffeaa7;
          border-radius: 6px;
          padding: 1rem;
          margin: 1rem 0;
          text-align: center;
        }

        .results-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1rem;
          margin-bottom: 1.5rem;
        }

        .result-card {
          padding: 1rem;
          border: 1px solid #e2e8f0;
          border-radius: 6px;
          background: #f7fafc;
          position: relative;
        }

        .result-header {
          display: flex;
          align-items: center;
          margin-bottom: 0.5rem;
        }

        .result-icon {
          font-size: 1.5rem;
          margin-right: 0.5rem;
        }

        .result-card h4 {
          margin: 0;
          color: #2d3748;
        }

        .result-card p {
          margin: 0 0 1rem 0;
          color: #718096;
          font-size: 0.9rem;
        }

        .download-btn {
          width: 100%;
          padding: 0.5rem 1rem;
          border: none;
          border-radius: 4px;
          color: white;
          font-weight: 500;
          cursor: pointer;
          transition: background-color 0.2s;
          margin-bottom: 0.5rem;
        }

        .download-btn:hover {
          opacity: 0.9;
        }

        .html-btn { background: #3182ce; }
        .zip-btn { background: #38a169; }
        .txt-btn { background: #d69e2e; }
        .fasta-btn { background: #805ad5; }
        .summary-btn { background: #718096; }

        .file-info {
          background: #edf2f7;
          padding: 0.5rem;
          border-radius: 4px;
          font-family: monospace;
          font-size: 0.8rem;
        }

        .debug-card {
          background: #fffaf0;
          border-color: #fed7aa;
        }

        .debug-info {
          font-size: 0.9rem;
        }

        .debug-info p {
          margin: 0.25rem 0;
          font-size: 0.9rem;
        }
      `}</style>
    </div>
  );
};